dist: xenial
language: python
sudo: false
python:
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install tox-travis
  - pip install coveralls
script:
  - tox
after_success:
  - coveralls
notifications:
  irc:
    - "irc.freenode.org#rapidsms"
